language: java
script: gradle dist

install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: MHztV5zxICtSJIKxFgVijbRVHWF2Jj/mc2a5RdfdAp75gGJvQySz07co7uiqp2yyfudQKamqysrezq5eksSVI16OQjC3MDOIr6Q/CggXbnoeuB6Vy9+O4DugKS8iikg9gYQZFiOhBg8nXpsbQQ3eBbAxq0L99U4NpR5TisUpSpU=
  file:
    - build/distributions/xmlcalabash1-xcc-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
