language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: NOIToratwXQdWShW5t31ZENlwgCs+V+jcHiQgUQT0IvPOl3tFpPUcdemN/Ow6KlZgAl9KDpJhG1EPKKV6dPYH+h+tVi9bkjA5pPd1X0RrsSSBTfwuJ+iEmP5rbp403xFZlirHY7zg6oSbEQ/gpLBkJwnDEPmQGzijNPbbEX5H2s=
  file:
    - build/distributions/xmlcalabash1-xcc-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
